SET search_path TO media_rating_app;

-- ################
-- USERS
-- ################
CREATE TABLE users (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) UNIQUE NOT NULL,
    pw_hash TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ################
-- USER PROFILE
-- ################
CREATE TABLE user_profiles (
    user_id INT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    display_name VARCHAR(50) NOT NULL,
    bio TEXT,
    avatar_url TEXT,
    total_ratings INT DEFAULT 0
);

-- ################
-- MEDIA BASE
-- ################
CREATE TYPE media_type as ENUM ('movie', 'series', 'game', 'book');

CREATE TABLE media_entries (
    id SERIAL PRIMARY KEY,
    creator_id INT NOT NULL DEFAULT 0 REFERENCES users(id) ON DELETE SET DEFAULT,
    title VARCHAR(255) NOT NULL,
    media_description TEXT,
    media_type media_type NOT NULL,
    release_date DATE,
    age_restriction INT,
    artwork_url TEXT,
    avg_rating NUMERIC(3,2) DEFAULT 0,
    rating_count INT DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- ################
-- MEDIA TYPE DETAILS
-- ################
CREATE TABLE movie_details (
    media_id INT PRIMARY KEY REFERENCES media_entries(id) ON DELETE CASCADE,
    duration_minutes INT NOT NULL
);

CREATE TABLE seasons (
    id SERIAL PRIMARY KEY,
    series_id INT REFERENCES media_entries(id) ON DELETE CASCADE,
    season_number INT NOT NULL,
    release_date DATE,
    UNIQUE (series_id, season_number)
);

CREATE TABLE episodes (
    id SERIAL PRIMARY KEY,
    season_id INT REFERENCES seasons(id) ON DELETE CASCADE,
    episode_number INT NOT NULL,
    title VARCHAR(255),
    duration_minutes INT,
    release_date DATE,
    UNIQUE (season_id, episode_number)
);

-- ################
-- RATINGS
-- ################
CREATE TABLE ratings (
    id SERIAL PRIMARY KEY,
    user_id INT NOT NULL DEFAULT 0 REFERENCES users(id) ON DELETE SET DEFAULT,
    media_id INT NOT NULL REFERENCES media_entries(id) ON DELETE CASCADE,
    stars INT CHECK (stars BETWEEN 1 AND 5),
    review TEXT,
    is_confirmed BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    like_count INT NOT NULL DEFAULT 0
);

CREATE UNIQUE INDEX idx_unq_user_media
ON ratings(user_id, media_id)
WHERE user_id <> 0;

-- ################
-- RATING LIKES
-- ################
CREATE TABLE rating_likes (
    user_id INT REFERENCES users(id) ON DELETE CASCADE,
    rating_id INT REFERENCES ratings(id) ON DELETE CASCADE,
    PRIMARY KEY (user_id, rating_id)
);

-- ################
-- FAVORITES
-- ################
CREATE TABLE favorites (
    user_id INT REFERENCES users(id) ON DELETE CASCADE,
    media_id INT REFERENCES media_entries(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    PRIMARY KEY (user_id, media_id)
);

-- ################
-- WATCHLIST
-- ################
CREATE TABLE watchlists (
    user_id INT REFERENCES users(id) ON DELETE CASCADE,
    media_id INT REFERENCES media_entries(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    PRIMARY KEY (user_id, media_id)
);

-- ################
-- GROUPING
-- ################
CREATE TABLE media_groups (
    id SERIAL PRIMARY KEY,
    group_name VARCHAR(255) NOT NULL,
    group_type VARCHAR(50) NOT NULL
);

CREATE TABLE media_group_links (
    group_id INT REFERENCES media_groups(id) ON DELETE CASCADE,
    media_id INT REFERENCES media_entries(id) ON DELETE CASCADE,
    PRIMARY KEY (group_id, media_id)
);

CREATE TABLE media_group_hierarchy (
    parent_group_id INT REFERENCES media_groups(id) ON DELETE CASCADE,
    child_group_id INT REFERENCES media_groups(id) ON DELETE CASCADE,
    PRIMARY KEY (parent_group_id, child_group_id)
);